frontend/modules/tutors/controllers/TutorsController.php
<?php

namespace app\modules\tutors\controllers;
use yii\filters\AccessControl;
use frontend\models\SignupForm;
use frontend\models\LoginForm;
use yii\helpers\Url;
use Yii;
use frontend\models\Course;
use frontend\models\User;
use yii\db\Expression;
use frontend\models\CourseAnnouncement;
use frontend\models\Utility;
use yii\data\ActiveDataProvider;
use frontend\models\TcCoursesSalesTransaction;

class TutorsController extends \yii\web\Controller
{
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                //'only' => ['index','signup'],
                'rules' => [
                    [
                        'actions' => ['index','signup'],
                        'allow' => true,
                        'roles' => ['?'],
                    ],
                   [
                        'actions' => ['dashboard','profile','index','signup'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
        ];
    }

    public function actionIndex()
    {
        $this->layout="@app/views/layouts/home_tutor";
        return $this->render('index');
    }

      public function actionDashboard()
    {
        $this->layout="@app/views/layouts/user_dashboard";
        $this->view->params['d_class']="current";
        $newcourse = new Course;
        $announcement = new CourseAnnouncement;
        $userid=Yii::$app->user->id;
        $newcourse->scenario="isguest";
        $searchModel = new \frontend\models\CourseSearch();
        $currentMonthData=TcCoursesSalesTransaction::getUserCurrentMonthData(Yii::$app->user->id,date("m"));
        $gross=round(TcCoursesSalesTransaction::getUserCurrentMonthGross($userid,date("m")),2);
        $net=round(TcCoursesSalesTransaction::getUserCurrentMonthNet($userid,date("m")),2);
        $dataProvider = $searchModel->searchTutorCourse(Yii::$app->request,$userid,4);
        return $this->render('dashboard',array("currentMonthData"=>$currentMonthData,"net"=>$net,"gross"=>$gross,"transaction"=>TcCoursesSalesTransaction::getTransaction($userid),"dataProvider"=>$dataProvider,"newcourse"=>$newcourse,"userid"=>$userid,"announcement"=>$announcement));
    }

    public function actionSignup(){

        //echo 1;

        //$this->layout="@app/views/layouts/main_guest";
      $coursecat = Utility::cleanString(Yii::$app->request->get("cc"));
      $coursetitle =Utility::cleanString(Yii::$app->request->get("c_title"));
        $model=new SignupForm();
        if(Yii::$app->user->isGuest){
          $model->scenario ="tutor";

          if($model->load(Yii::$app->request->post())){

              if($user = $model->tutorsignup()){

                  if(Yii::$app->getUser()->login($user)){
                       LoginForm::setSession($user);
                       \Yii::$app->mailer->compose(['html' => 'signupComplete-html'], ['user' => $user])
                      ->setFrom([\Yii::$app->params['supportEmail'] => \Yii::$app->name])
                      ->setTo($user->email)
                      ->setSubject('Welcome to ' . \Yii::$app->name)
                      ->send();
                      return $this->redirect(array("/course/basicinfo",'slug'=>Yii::$app->session->get("new_course_slug")));
                  }

              }

          }
            else{
                //print_r(Yii::$app->request->get());
               //// echo "ds";
            }


        }
        else {
          if($model->load(Yii::$app->request->post())){
            $user = User::findOne([Yii::$app->user->id]);
            $user->roleid=2;
            $transaction = $user->getDb()->beginTransaction();
            $user->save();
            $course= new Course(['scenario' => 'isguest']);
            $course->course_title=$model->course_title;

            $course->course_category=$model->coursecat;
            $course->owner = Yii::$app->user->id;

            //CourseCategory::convertToInt($this->coursecat);
            if($course->save()){
                $instructors=  new \frontend\models\CourseInstructors();
                $instructors->course_id=$course->getPrimaryKey();
                $instructors->user_id=Yii::$app->user->id;
                if($instructors->save()){
                     $transaction->commit();
                        //if(!Yii::$app->session->isActive)
                            //    Yii::$app->session->open();

                    Yii::$app->session->set("new_course",$course->course_id);
                }
                else
                    print_r($instructors->getErrors());
                //return $this->redirect(array("/course/basicinfo",'slug'=>Yii::$app->session->get("new_course_slug")));

           }

        }
        }
          return $this->render('signup', [
            'model' => $model,
            'coursecat'=>$coursecat,
            'coursetitle'=>$coursetitle
        ]);

    }

}

frontend/modules/tutors/views/tutors/_tutors_courses.php
<?php
  use yii\helpers\Url;
  use frontend\models\Course;
 ?>


 <!-- <div class="tutors_course_item row" >
      <div class="course_banner col-md-3">
          <img src="<?php //Course::getCourseBanner($model->course_banner)?>" alt="<?php //$model->course_title?>"/>
      </div>
      <div class="course_details col-md-9">
          <div><?php //$model->course_title?></div>
          <div><span><?php //Course::getStatusString($model->status)?></span></div>
          <div><span></span></div>
      </div>
 </div> -->

   <?=Course::createTutorsCourseAd($model);?>
  

frontend/modules/tutors/views/tutors/dashboard.php
<?php
use yii\helpers\Url;
use yii\helpers\Html;
use yii\widgets\ActiveForm;
use frontend\models\Course;
use frontend\models\User;
use frontend\models\CourseCategory;
use yii\bootstrap\Modal;
use marqu3s\summernote\Summernote;
use yii\widgets\ListView;
use yii\widgets\Pjax;
use scotthuangzl\googlechart\GoogleChart;
use yii\bootstrap\BootstrapPluginAsset;
use frontend\models\TcCoursesSalesTransaction;
?>
<style>
  .btn-default{
        height: 34px;
  }
  .modal-dialog {
    max-width: 600px !important;
}
#announcementModal .modal-dialog {
    max-width: 600px !important;
}
</style>

   <!-- END / CONTENT BAR -->
<!-- COURSE CONCERN -->
    <section  class="tutor_content_bg">
        <div class="container">
            <?php if(Yii::$app->session->hasFlash("error")):?>
             <div class="alert alert-danger"><?=Yii::$app->session->getFlash('error')?></div>
            <?php elseif(Yii::$app->session->hasFlash("success")):?>
                <div class="alert alert-success"><?=Yii::$app->session->getFlash('success')?></div>
            <?php endif?>
            <!-- <div class="price-course">
                <i class="icon md-database"></i>
                <h3>Available Balance </h3>
                <span>$0.0</span>
                <div class="create-coures">
                    <a href="#addsection" class="mc-btn btn-style-1 popup-with-zoom-anim">Create new course</a>
                    <a href="#" class="mc-btn btn-style-5">Request Payment</a>
                </div>

            </div> -->

            <div class="row" id="dashboard_sec">
              <div class="col-md-6" id="earnings">
                <div class="col-md-12" id="monthly-earning-chart">
                  <?php //print_r($currentMonthData)?>
                  <?=
                   GoogleChart::widget(array('visualization' => 'LineChart',
                   'data' => $currentMonthData,

                   'options' => array("height"=>"400",
                   'title' => 'Earning for this month',
                  //  'hAxis' => [
                  //        'title' => 'Year',
                  //        'titleTextStyle' => [
                  //            'color' => '#333'
                  //        ]
                  //    ],
                   "legend"=>[ "position"=> "top" ],
                   'chatArea'=>["left"=>"5em","top"=>"20px","width:100%","height"=>"400"],
                   'colors'=>["#ef4132","#4caf50"]
                  )));
                  ?>
                </div>
                <div class="row col-md-12">
                    <div id="gross" class="col-sm-6  col-xs-6  col-md-6 gross-net">
                        <strong><span>Gross Revenue</span></strong>
                        <h1>$<?=$gross?></h1>
                    </div>
                  <div id="net" class="col-sm-6  col-xs-6 col-md-6 gross-net">
                        <span>Net Revenue</span>
                        <h1>$<?=$net?></h1>
                    </div>
                </div>
                <div class="col-md-12" id="transactions">
                  <!-- <div class="table table-stripe">
                    <div class="thead">
                      <span class="th">Transaction ID</span>
                      <span class="th">Date</span>
                      <span class="th">Amount</span>
                    </div>
                      <div class="tr">
                        <span class="td">Row 1, Cell 1</span>
                        <span class="td">Row 1, Cell 2</span>
                        <span class="td">Row 1, Cell 3</span>
                      </div>
                      <div class="tr">
                        <span class="td">Row 2, Cell 1</span>
                        <span class="td">Row 2, Cell 2</span>
                        <span class="td">Row 2, Cell 3</span>
                      </div>
                    </div> -->
                      <table class="table table-stripe">
                          <thead>
                            <tr><th>Transaction ID</th><th>Date</th><th>Gross</th><th>Net</th></tr>
                          </thead>

                            <?php Pjax::begin(["id"=>"pjax_transactions"]); ?>
                              <?=
                                  ListView::widget([
                                  'dataProvider' => $transaction,
                                  'emptyText'=>"No transaction",
                                  'options' => [
                                      'tag' => 'tbody',
                                      'class' => '',
                                          ],
                                  'itemView'=>function($model,$key,$index){
                                          return "<tr><td>#".$model["transactionid"]."</td><td>".$model["date"]."</td><td>$".$model["amount"]."</td><td>$".TcCoursesSalesTransaction::doCommission($model["owner"],$model["coupon_code"],$model["amount"])."</td></tr>";
                                    },
                                      'layout' => "{items}\n {pager}",
                                  ]);


                                ?>
                              <?php Pjax::end(); ?>
                      </table>
                </div>

              </div>
                  <div class="col-md-6">
                    <div class="create-coures text-right">
                        <a href="#createCourseModal" data-target="#createCourseModal" data-toggle="modal"  class="custom-btn grey-btn ">
                          <span></span>
                          Create a course</a>
                        <!-- <a href="#" class="mc-btn btn-style-5">Request Payment</a> -->
                    </div>

                    <div id="tut-list-wrapper">

                      <div id="search_filter" class="col-md-12">
                          <div class="col-md-6 text-left search-div" >
                            <?php ActiveForm::begin(["method"=>"get",'options' => ['data-pjax' => true ]])?>
                              <div class="input-group add-on">
                                    <input id="searchfield" class="form-control" type="text" name="q" placeholder="Search for your course"/>
                                    <div class="input-group-btn">
                                      <button class="btn btn-default" type="submit"><i class="fa fa-search"></i></button>
                                    </div>
                                  </div>
                                <!-- <input id="searchfield" class="form-control" type="text" name="searchfilter" placeholder="Search for your course"/> -->
                            <?php ActiveForm::end();?>
                          </div>
                          <div class="col-md-6 text-right sorter-div">

                            <?php $form=ActiveForm::begin(["id"=>"sorter-form","method"=>"get",'options' => ['data-pjax' => true ]])?>
                                <select  id="sorter" name="sorter" class="form-control">
                                    <option value="newest">Sort By Newest</option>
                                    <option value="oldest">Oldest</option>
                                    <option value="title-asc">Title Ascending</option>
                                    <option value="title-desc">Title Descending</option>
                                    <option value="1">Published</option>
                                    <option value="4">Pending Publish</option>
                                    <option value="3">Pending Review</option>
                                    <option value="2">Draft</option>
                                </select>
                            <?php ActiveForm::end()?>
                          </div>
                        </div>
                        <?php Pjax::begin(["id"=>"pjax_tutors"]); ?>
                          <?=
                              ListView::widget([
                              'dataProvider' => $dataProvider,
                              'emptyText'=>"You have not created any course yet. ",
                              'options' => [
                                  'tag' => 'div',
                                  'class' => '',
                                  'id' => 'tutor-course-list-wrapper',
                                      ],
                              'itemView'=>"_tutors_courses",
                                  'layout' => "{items}\n <div class='clear'></div>{pager}{summary}<div class='clear'></div>",
                              ]);


                            ?>
                          <?php Pjax::end(); ?>
                    </div>

                </div>
              </div>
    </section>
    <!-- END / COURSE CONCERN -->


<!-- SECTIONS -->
<div class="modal fade" id="createCourseModal" tabindex="-1" role="dialog" aria-labelledby="createCourseModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
        <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" ><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
            <h4 class="modal-title" id="myModalLabel">Create a Course</h4>
        </div>
        <div class="modal-body" >
                <div class="row">

                        <div class="row col-md-12 row">
                            <!-- start ActiveForm -->
                              <?php $form= ActiveForm::begin(['action'=>Url::base().'/course/createcourse','options'=>['method'=>"post"]])?>
                            <div class="col-md-12">
                              <?=$form->field($newcourse,'course_title')->textInput(['maxlength'=>70,"placeholder"=>"Course name max 70 characters"])->label(false)?>

                            </div>
                            <div class="col-md-12">
                              <div class="form-group">
                                <?=  Html::dropDownList("Course[course_category]",null,CourseCategory::getCategory(),['prompt'=>"Select course category",'class'=>"form-control"]) ?>
                              </div>
                            </div>
                            <div class="col-md-offset-3 col-md-offset-right-3 col-md-6">
                                <div class="form-group">
                                  <input type="submit" class="btn btn-success form-control" value="Create"/>
                                </div>
                            </div>
                        </div>
                       <?php ActiveForm::end(); ?>
                    </div>



           <div class="modal-footer">

            </div>
          </div>
        </div>

    </div>

</div>
<div class="modal fade" id="announcementModal" tabindex="-1" role="dialog" aria-labelledby="flagabuse">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">Make an Announcements</h4>
      </div>
      <div class="modal-body">
          <div id="alert-flag-success" class="alert alert-success" style="display:none"></div>
          <div id="alert-flag-error"  class="alert alert-danger " style="display:none"></div>
        <?php $form=ActiveForm::begin(['id'=>'announcementform','action'=>Url::toRoute("/course/saveannouncement"),'options'=>[]]);?>

        <div>
            <?= $form->field($announcement,"title")->textInput(['placeholder'=>"Enter title"])->label(false)?>
        </div>
          <input type="hidden" name="returnUrl" value="<?=Url::current()?>"/>
          <?= $form->field($announcement,"userid")->hiddenInput(['value'=>Yii::$app->user->id])->label(false)?>
          <?= $form->field($announcement,"courseid")->hiddenInput(['value'=>''])->label(false)?>
         <div>
            <?=
                    $form->field($announcement, 'comment')->widget(Summernote::className(),
                                 ['clientOptions' => ["height"=>"100",'toolbar'=>[['para', ['ul', 'ol', 'paragraph']],['style',['bold','italic','underline']]]]])->label(false)

             ?>

          </div>


      <div class="modal-footer">
        <input type="submit" class="btn btn-success" id="saveflag" value="Submit"/>
      </div>
        </div>
          <?php ActiveForm::end();?>
    </div>
  </div>
</div>
<?php
$script=<<<EOD
$(window).resize(function(){
  drawChartw0();
});

$(".announcement").click(function(){
   $("#courseannouncement-courseid").val($(this).data("courseid"))
})
EOD;

$this->registerJS($script);

 ?>

frontend/modules/tutors/views/tutors/index.php
<?php
    use yii\helpers\Url;
    use yii\helpers\Html;
    use frontend\models\CourseCategory;
     use yii\helpers\ArrayHelper;
?>
<!-- banner starts here -->

<header>
    <div class="header-content">
        <div class="header-content-inner text-left">
            <h1>Join our online tutors</h1>
            <p>And Monitize your knowledge</p>
            <a href="#howitworks" class="btn btn-primary btn-xl page-scroll">How it work</a>
            <a href="<?=Url::toRoute("/tutors/signup")?>" class="btn btn-secondary btn-xl page-scroll">Create a course</a>
        </div>
    </div>
</header>

<!-- banner ends here -->
   <!-- teachsity starts here -->

    <section>
        <div class="container teachsity-gives">
            <div class="row">
                <div class="col-lg-12 text-center">
                    <h2 class="section-heading-height">Teachsity gives you...</h2>
                </div>
            </div>
        </div>
        <div class="container">
            <div class="row">
                <div class="col-sm-6 col-xs-12 col-lg-3 col-md-6 text-center">
                    <div class="service-box">
                        <img src="<?=Url::base()?>/images/24x7.png" alt="24x7">
                        <h3>24x7 Support</h3>
                        <p class="text-muted text-left">Use Teachsity support community, get your questions answered by our active community support team.</p>
                    </div>
                </div>
                <div class="col-sm-6 col-xs-12 col-lg-3 col-md-6 text-center">
                    <div class="service-box">
                        <img src="<?=Url::base()?>/images/easyuse.png" alt="easyuse">
                        <h3>Easy-to-use Tools</h3>
                        <p class="text-muted text-left">Teachsity provides easy-to-use course creation tools to let you build your courses with ease.</p>
                    </div>
                </div>
                <div class="col-sm-6 col-xs-12 col-lg-3 col-md-6 text-center">
                    <div class="service-box">
                        <img src="<?=Url::base()?>/images/absolutecontroll.png" alt="absolutecontroll">
                        <h3>Absolute Control</h3>
                        <p class="text-muted text-left">Teachsity provides free course hosting but let you control your course content. You can reuse your course content as much as you wish.</p>
                    </div>
                </div>
                <div class="col-sm-6 col-xs-12 col-lg-3 col-md-6 text-center">
                    <div class="service-box">
                        <img src="<?=Url::base()?>/images/onlinebrand.png" alt="onlinebrand">
                        <h3>Build an Online Brand</h3>
                        <p class="text-muted text-left">Build and online brand on Teachsity, get to know your audience and become famous in what you teach.</p>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- teachsity ends here -->

    <!-- heow it work starts here -->

    <aside class="bg-dark">
        <div class="container">
            <div class="row" id="howitworks">
                <div class="col-lg-12 text-center">
                    <h2 class="section-heading-height">How it Works</h2>
                </div>
            </div>
        </div>
        <div class="container">
            <div class="row">
                <div class="col-sm-6 col-xs-12 works-box works-border-bottom works-border-right">
                  <div class="row margin-mutted">
                    <div class="col-sm-4 col-xs-12 padding-mutted">
                      <p class="text-center img-margine"><img src="<?=Url::base()?>/images/imagin.png" alt="imagine"></p>
                    </div>
                    <div class="col-sm-8 col-xs-12 padding-mutted">
                      <h3 class="img-sub-head">Imagine</h3>
                      <p class="img-sub-cont">There are no limit to what you can teach on Teachsity. Become famous for what you do best.</p>
                    </div>
                  </div>
                </div>
                <div class="col-sm-6 col-xs-12 works-box works-border-bottom">
                  <div class="row margin-mutted">
                    <div class="col-sm-4 col-xs-12 padding-mutted">
                      <p class="text-center img-margine"><img src="<?=Url::base()?>/images/design.png" alt="design"></p>
                    </div>
                    <div class="col-sm-8 col-xs-12 padding-mutted">
                      <h3 class="img-sub-head">Design</h3>
                      <p class="img-sub-cont">Use our easy-to-use course creation tool to build your online course.</p>
                    </div>
                  </div>
                </div>
            <div class="col-sm-6 col-xs-12 works-box works-border-right">
              <div class="row margin-mutted">
                <div class="col-sm-4 col-xs-12 padding-mutted">
                  <p class="text-center img-margine"><img src="<?=Url::base()?>/images/teach.png" alt="teach"></p>
                </div>
                <div class="col-sm-8 col-xs-12 padding-mutted">
                  <h3 class="img-sub-head">Teach</h3>
                  <p class="img-sub-cont">Teach millions of hungry student ready to learn, anytime and on any device.</p>
                </div>
              </div>
            </div>
            <div class="col-sm-6 col-xs-12 works-box">
              <div class="row margin-mutted">
                <div class="col-sm-4 col-xs-12 padding-mutted">
                  <p class="text-center img-margine"><img src="<?=Url::base()?>/images/earn.png" alt="earn"></p>
                </div>
                <div class="col-sm-8 col-xs-12 padding-mutted">
                  <h3 class="img-sub-head">Earn</h3>
                  <p class="img-sub-cont">Monitize your expertise, Earn handsomely while impacting positively on the world. </p>
                </div>
              </div>
            </div>
            </div>
        </div>
    </aside>
    <!-- heow it work ends here -->

    <!-- join teachsity start here -->

    <section class="2nd-bg who-can-join">
        <div class="container">
            <div class="row">
                <div class="col-lg-12 text-center">
                    <h2 class="section-heading-height">Who Can Join Teachsity</h2>
                </div>
            </div>
        </div>
        <div class="container">
            <div class="col-xs-12 col-sm-4 padding mutted ">
              <div class="thumbnail">
                  <div class="thumb-bg">
                    <img src="<?=Url::base()?>/images/expert-icn.png">
                  </div>
              </div>
            </div>
            <div class="col-xs-12 col-sm-4 padding mutted">
              <div class="thumbnail">
                  <div class="thumb-bg">
                    <img src="<?=Url::base()?>/images/instructor-icn.png">
                  </div>
              </div>
            </div>
            <div class="col-xs-12 col-sm-4 padding mutted">
              <div class="thumbnail">
                  <div class="thumb-bg">
                    <img src="<?=Url::base()?>/images/hobby-list-icn.png">
                  </div>
              </div>
            </div>
        </div>
    </section>
    <!-- join teachsity ends here -->

    <!-- faq start here -->

    <aside class="bg-light">
        <div class="container text-center">
            <div class="section-heading-height">
                <h2>FAQ</h2>
            </div>
        </div>
        <div class="container">
          <div class="row faq-div">
             <div class="col-md-offset-2 col-md-offset-right-2 col-md-8 ">

           <div id="accordion-first" class="clearfix">
              <div class="accordion" id="accordion2">
                <div class="accordion-group">
                  <div class="accordion-heading">
                    <a class="accordion-toggle collapsed" data-toggle="collapse" data-parent="#accordion2" href="#collapseOne">
                      <em class="icon-fixed-width fa fa-plus"></em>Are my account details safe with you?
                    </a>
                  </div>
                  <div style="height: 0px;" id="collapseOne" class="accordion-body collapse">
                    <div class="accordion-inner">
                    Teachsity strive to ensure maximum security of our user account details. Our team employs procedural and technological measures to secure users account details.
                    </div>
                  </div>
                </div>
                <div class="accordion-group">
                  <div class="accordion-heading">
                    <a class="accordion-toggle collapsed" data-toggle="collapse" data-parent="#accordion2" href="#collapseTwo">
                      <em class="icon-fixed-width fa fa-plus"></em>When do I get paid if someone purchases my course?
                    </a>
                  </div>
                  <div style="height: 0px;" id="collapseTwo" class="accordion-body collapse">
                    <div class="accordion-inner">
                      Teachsity tutors get paid on a monthly bases, but a tutor can request for payment at any point without any minimum amount requirement.
                    </div>
                  </div>
                </div>
                <div class="accordion-group">
                  <div class="accordion-heading">
                    <a class="accordion-toggle collapsed" data-toggle="collapse" data-parent="#accordion2" href="#collapseThree">
                      <em class="icon-fixed-width fa fa-plus"></em>What is the commission that I pay to you?
                    </a>
                  </div>
                  <div style="height: 0px;" id="collapseThree" class="accordion-body collapse">
                    <div class="accordion-inner">
                      Since we operate a commission based system. Click <a href="http://support.teachsity.com/revenue-share">here</a> to see Teachsity’s commission breakdown.
                    </div>
                  </div>
                </div>
                  <div class="accordion-group">
                  <div class="accordion-heading">
                    <a class="accordion-toggle collapsed" data-toggle="collapse" data-parent="#accordion2" href="#collapseFour">
                      <em class="icon-fixed-width fa fa-plus"></em>Can I become a full time tutor for you?
                    </a>
                  </div>
                  <div style="height: 0px;" id="collapseFour" class="accordion-body collapse">
                    <div class="accordion-inner">
                     Teachsity do not keep a tutor on payroll we only work with tutors that are freelancers.
                    </div>
                  </div>
                </div>
                <div class="accordion-group">
                  <div class="accordion-heading">
                    <a class="accordion-toggle collapsed" data-toggle="collapse" data-parent="#accordion2" href="#collapseFive">
                      <em class="icon-fixed-width fa fa-plus"></em>How do you make sure my course is not stolen? 
                    </a>
                  </div>
                  <div style="height: 0px;" id="collapseFive" class="accordion-body collapse">
                    <div class="accordion-inner">
                      Teachsity strive to protect course contents on our platform. We keep an eye on the internet to ensure that there has been no leakage of course content, if any we apply some legal means to checkmate the leakage. We all trademark every course content on Teachsity.
                    </div>
                  </div>
                </div>
                  <div class="accordion-group">
                  <div class="accordion-heading">
                    <a class="accordion-toggle collapsed" data-toggle="collapse" data-parent="#accordion2" href="#collapseSix">
                      <em class="icon-fixed-width fa fa-plus"></em>Do you’ll support in case i get stuck with some issue? 
                    </a>
                  </div>
                  <div style="height: 0px;" id="collapseSix" class="accordion-body collapse">
                    <div class="accordion-inner">
                      We have a 24/7 support service that is ready to help you out when you get stuck. Email us on support@teachsity.com
                    </div>
                  </div>
                </div>
              </div><!-- end accordion -->
          </div>
          </div>
        </div>
      </div>
    </aside>

  <!-- faq ends here -->