frontend/controllers/PaymentController.php
<?php

namespace frontend\controllers;

use yii\filters\AccessControl;
use yii\base\InvalidParamException;
use yii\web\BadRequestHttpException;
use yii\filters\VerbFilter;
use frontend\models\Course;
use yii\helpers\Url;
use yii;
use frontend\models\CourseCoupons;
use Razorpay\Api\Api;

class PaymentController extends \yii\web\Controller
{
    const RAZOR_API_KEY ="rzp_test_2IKJLNW0vMjOww";
    const RAZOR_API_SECRET ="Fb2Xv7883qPTLmUdn6fMRakS";
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                //'only' => ['logout', 'signup'],
                'rules' => [
                    /*[
                        'actions' => ['signup'],
                        'allow' => true,
                        'roles' => ['?'],
                    ],*/
                    [
                        'actions' => ['make-paypal-payment','make-payment','checkout','payment-cancel','payment-success','test','razor-pay-capture'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'razor-pay-capture' => ['post'],
                    
                ],
            ],
        ];
    }
    public function actionCheckout($id){
      //  Url::remember();
        $course = Course::findOne([$id]);
        Yii::$app->session["pcid"]=$course;
        $coupon = Yii::$app->request->get("coupon");
        $original_amount=Course::getPriceByInstance($course);
        $total_amount= $original_amount;
        $discount=0;
        $rate=0;
        $totalAmountWithNoCurrency = Course::getPriceNoCurrency($course);
        $paiseAmount = Course::convertToPaise($totalAmountWithNoCurrency);
        

        if(!empty($coupon)){
          if(CourseCoupons::find()->where(["courseid"=>$id,"coupon_code"=>$coupon])->exists()){
            $_coupon=CourseCoupons::find()->where(["courseid"=>$id,"coupon_code"=>$coupon])->one();
            if(strtotime("today") >=strtotime($_coupon->expirey_date)){
                    Yii::$app->session->setFlash("error","The applied coupon has expired.");
                  //  return $this->redirect(Url::previous());

              }
           else{
              $totalAmountWithNoCurrency = Course::getPriceNoCurrency($course,$_coupon->discount);
              $paiseAmount = Course::convertToPaise($totalAmountWithNoCurrency);
              $total_amount = Course::getPriceByInstance($course,$_coupon->discount);//()
              $discount=CourseCoupons::getDiscountAmount($course->amount,$_coupon->discount);//
              $rate =$_coupon->discount;
           }
          }
          else{
            Yii::$app->session->setFlash("error",'Sorry this coupon does not exist');
          //  return $this->redirect(Url::previous());
          }
        }
        
        // save the actual paise amount is session to enable capturing thesame value
        $session = Yii::$app->session;
        $session->set("paiseAmount",$paiseAmount);;
        
        
        return $this->render("checkout",["course"=>$course,"rate"=>$rate,"discount"=>$discount,"coupon"=>$coupon,"total_amount"=>$total_amount,"amount"=>$original_amount,"totalAmountWithNoCurrency"=>$totalAmountWithNoCurrency,"paiseAmount"=>$paiseAmount]);
    }
    
    public function actionRazorPayCapture(){
        $session = Yii::$app->session;
        $coursePrice = $session->get("paiseAmount");
        $course = $session->get("pcid");
        $coupon = Yii::$app->request->post("coupon");
        
        $paymentId = Yii::$app->request->post("paymentId");
//        $coursePrice = Yii::$app->request->post()->get("coursePrice");
        $api = new Api(PaymentController::RAZOR_API_KEY, PaymentController::RAZOR_API_SECRET);
        
        $payment = $api->payment->fetch($paymentId);
        $payment->capture(array('amount' =>$coursePrice ));
        
        $session->remove("paiseAmount");
        if ($payment->error_code ==null && $payment->status =="captured"){
                if(!\frontend\models\Enrollment::find()->where(['courseid'=>$course->course_id,"userid"=>Yii::$app->user->id])->exists()){
                   $enroll = new \frontend\models\Enrollment;
                   $enroll->courseid=$course->course_id;
                   $enroll->userid=Yii::$app->user->id;

                   if(!$enroll->save()){
                      Yii::$app->session->setFlash("error","An error occurred while trying to enroll you for \"".$course->course_title."\"");
                       //$this->redirect(Url::toRoute(["learn","slug"=>$course->slug]));
                   }
               }
               $payment= new \frontend\models\TcCoursesSalesTransaction();
               $payment->payment_source="razorpay";
               $payment->courseid=$course->course_id;
               $payment->status ="captured";
               $payment->userid=Yii::$app->user->id;
               $payment->coupon_code=$coupon;
               $payment->save();
               return 1;
        }
        else{
            Yii::$app->response->statusCode = 500;
            return 0;
        }
        // To get the payment detail
        
    }
    public function actionMakePaypalPayment($tid){
      $course = Course::findOne([$tid]);
      $code=Yii::$app->request->get("coupon");
      $amount = Course::getPrice($course->course_id);//
      //check coupon validity;
      if(!empty($code))
      {
        if(CourseCoupons::find()->where(["courseid"=>$course->course_id,"coupon_code"=>$code])->exists()){
          $coupon=CourseCoupons::find()->where(["courseid"=>$course->course_id,"coupon_code"=>$code])->one();
          if(strtotime("today") >=strtotime($coupon->expirey_date)){
                  Yii::$app->session->setFlash("error","The applied coupon has expired.");
                  return $this->redirect(Url::previous());
            }
         else{
            $amount = Course::getPrice($course->course_id,$coupon->discount);//

         }
        }
        else{
          Yii::$app->session->setFlash("error",'Sorry this coupon does not exist');
          return $this->redirect(Url::previous());
        }
      }
      //Yi::$app->session["cc"]=$code;//store coupon code
      //https://api.sandbox.paypal.com/v1
      //store courseid in session to be used after payment process;
      // $access_token_request= shell_exec('curl -v https://api.sandbox.paypal.com/v1/oauth2/token -H "Accept: application/json" -H "Accept-Language: en_US" -u "AQ-MjLoafAKkrENBkvyPgMubFNVN5-1YmIwuM9ejZNLjxaPPR0O_xZudSdBsQ7NMLt5B-flFZT6CeL3M:EIbrdd7mVC6MB-GfYxnH_l8p-3OZ4dIuPusObqU__ZIIfsGN1TR4tSLtoX_aIMfjNGUem35RmtcHlX4W" -d "grant_type=client_credentials"');
      $access_token_request= shell_exec('curl -v https://api.paypal.com/v1/oauth2/token -H "Accept: application/json" -H "Accept-Language: en_US" -u "AagLuWa5Eq6snwST6fLHPekvoJ8n5Vti88tMNPOTf7hyEDhoWsgvqiL7zAVZGinoabxtCRnnUmeeTmoI:EIrz-_j6CndyDB9HcJI82b19odxuGSXqJaOCrnQLDOaF3rHGuszXyFyi2lQNYzQtXqR6pgSGENcu4VIT" -d "grant_type=client_credentials"');
      $access_token_request =json_decode($access_token_request,true);
      Yii::$app->session["pp_access_token"]=$access_token_request["access_token"];//save access_token to session;

      $payment_request= shell_exec('curl -v https://api.paypal.com/v1/payments/payment \
       -H "Content-Type: application/json" \
       -H "Authorization: Bearer '.$access_token_request["access_token"].'" \
       -d \'{
         "intent":"sale",
         "redirect_urls":{
           "return_url":"http://teachsity.com/payment/payment-success",
           "cancel_url":"http://teachsity.com/payment/payment-cancel"
         },
         "payer":{
           "payment_method":"paypal"
         },
         "transactions":[
           {
             "amount":{
               "total":"'.$course->amount.'",
               "currency":"INR"
             },
              "description": "Course payment - '.$course->course_title.' on teachsity.com."
           }
         ]
       }\'');


       $payment_request = json_decode($payment_request,true);

       if($payment_request["state"]=="created"){
           $payment= new \frontend\models\TcCoursesSalesTransaction();
           $payment->payment_source="paypal";
           $payment->courseid=$course->course_id;
           $payment->status ="created";
           $payment->userid=Yii::$app->user->id;
           $payment->coupon_code=$code;
           $payment->save();
           Yii::$app->session["transactionid"]=$payment->getPrimaryKey();

           $links=$payment_request["links"];//get links

           if($links[1]["rel"]=="approval_url"){
             $approval_url =$links[1]["href"];//get approval url to redirect user.
             return $this->redirect($approval_url);
           }
       }
       else {
         Yii::$app->session->setFlash("error","We were unable to intiate a transaction with paypal. Please try again.");
         return $this->redirect(array("payment-cancel"));
       }
    }

        public function actionPaymentSuccess(){
         
          $course= Yii::$app->session["pcid"];
          Yii::$app->session["pcid"]="";
          //check if this is paypal payment.
          if(Yii::$app->request->get("paymentId") && Yii::$app->request->get("PayerID") ){
            $transactionid = Yii::$app->session["transactionid"];
            $trans = \frontend\models\TcCoursesSalesTransaction::findOne([$transactionid]);
            $payer_id =Yii::$app->request->get("PayerID");
            $paymentId = Yii::$app->request->get("paymentId");
            $trans->status="approved";


            $accesstoken = Yii::$app->session["pp_access_token"];
            $execute_payment = shell_exec('curl -v https://api.sandbox.paypal.com/v1/payments/payment/PAY-6RV70583SB702805EKEYSZ6Y/execute/ \

frontend/views/payment/checkout.php
<?php
  use yii\helpers\Url;

 ?>
<!-- SUB BANNER -->

<style type="text/css">


	.course-top .container {
    	padding-bottom: 10em;
    	padding-top: 2em;
	}
</style>


<script src="https://checkout.razorpay.com/v1/checkout.js"></script>
<?php
$script=<<<EOD

var options = {
    "key": "rzp_test_2IKJLNW0vMjOww",
    "amount": "$paiseAmount", // 2000 paise = INR 20
    "name": "Teachsity",
    "description": "Course purchase:$course->course_title",
    "image": "http://104.131.190.147/images/logo-with-text.gif",
    "handler": function (response){
         
        $.ajax({
            method:"post",
            data:{"paymentId":response.razorpay_payment_id,"coupon":"$coupon"},
            url:"/payment/razor-pay-capture",
            beforeSend:function(){
                $(".pop_loader").show();
            },
            success:function(data){
                console.log(data)
                $(".pop_loader").hide();
                 window.location.href= "/payment/payment-success?pm=rzpy"
            },
            error:function(){
                $(".pop_loader").hide();
                window.location.href= "/payment/payment-cancel"
            }
        })
    },
    "prefill": {
        "name": "Harshil Mathur",
        "email": "harshil@razorpay.com"
    },
    "notes": {
        "address": "Hello World"
    },
    "theme": {
        "color": "#ccc"
    }
};
var rzp1 = new Razorpay(options);



    $("#rzp-button1").click(function(e){
        rzp1.open();
        e.preventDefault();
    });

EOD;

$this->registerJs($script);
?>

    <!-- COURSE -->
    <section class="course-top">
        <div class="container">
            <div class="row">
              <?php if(Yii::$app->session->hasFlash("error")):?>
                      <div class="col-md-12">
                        <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
                        <div class="alert alert-danger text-center">  <?=Yii::$app->session->getFlash("error");?> </div>
                       </div>
               <?php endif;?>
                <div class="col-md-8  col-md-offset-2" style="padding-top: 1.5em;">

                    <div class="tabs-page">
                    <h5 class="text-center black bold">Review Purchase</h5>
                        <!-- Tab panes -->
                        <div class="tab-content">
                            <div class="purchase-table">
                            	<table class="table table-strip">
                            		<tr>
                            			<td colspan="3"><?=$course->course_title?></td>
                            			<td><?=$amount?></td>
                            		</tr>
                                <?php if(!empty($coupon)):?>
                                  <tr>
                              			<td colspan="3"><?=$rate?>% discount with coupon (<?=$coupon?>)</td>
                              			<td>$<?=$discount?></td>
                              		</tr>
                                <?php endif?>
                            		<!-- <tr>
                            			<td colspan="3">Coupon 449823</td>
                            			<td>$19</td>
                            		</tr> -->
                            		<tr>
                            			<td colspan="3">Total</td>
                            			<td><?=$total_amount?></td>
                            		</tr>
                            	</table>
                            </div>
                            <div class="payment-methods row">
															<div class="col-md-6 text-center">
																			<a class="btn btn-sky"  href="<?=Url::toRoute(["make-paypal-payment","tid"=>$course->course_id,"coupon"=>$coupon])?>"> Pay with Paypal</a>
															</div>

                                                <div class="col-md-6 text-center">
                                                    <button id="rzp-button1">Pay</button>
                                                                    
                                                </div>

                            </div>
                         </div>


                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- END / COURSE TOP -->

frontend/views/payment/payment-cancel.php
<?php
  use yii\helpers\Url;

 ?>
<!-- SUB BANNER -->

<style type="text/css">


    .course-top .container {
        padding-bottom: 10em;
        padding-top: 2em;
    }
</style>

    <!-- COURSE -->
             <div class="row pay-ment-success">

                <div class="col-md-8  col-md-offset-2" style="padding-top: 1.5em;">

                    <div class="tabs-page" style="padding:20px">
                     <div class="alert alert-danger"><h4 class="text-center title"> <i class="fa fa-times fa-2x" style="color:#BF6F6F"></i> &nbsp;We were unable to complete your transaction.</h4></div>
                        <!-- Tab panes -->
                        <div class="tab-content">
                             <?php if(Yii::$app->session->hasFlash("error")):?>
                               <h4 class="text-center black bold">  <?=Yii::$app->session->getFlash("error");?> </h4>
                            <?php endif;?>
                            <div class="payment-methods row">
                                 <div class="col-md-12 text-center">
                                            <a class="btn btn-default"  href="<?=Url::toRoute("/course")?>"> Back to courses</a>
                                 </div>
                            </div>
                         </div>


                        </div>
                    </div>
                </div>

    <!-- END / COURSE TOP -->

frontend/views/payment/payment-success.php
<?php
  use yii\helpers\Url;

 ?>
<!-- SUB BANNER -->

<style type="text/css">


    .course-top .container {
        padding-bottom: 10em;
        padding-top: 2em;
    }
</style>

    <!-- COURSE -->
            <div class="row pay-ment-success" >

                <div class="col-md-8  col-md-offset-2" style="padding-top: 1.5em;">

                    <div class="tabs-page" style="padding:20px">
                    <div class="alert alert-success"><h4 class="text-center title"> <i class="fa fa-check-circle fa-2x" style="color:green"></i> &nbsp;Your payment was successfull!</h4></div>
                        <!-- Tab panes -->
                        <div class="tab-content">
                            <div class="purchase-table">
                            <?php if(Yii::$app->session->hasFlash("error")):?>
                               <h4 class="text-center black bold">  <?=Yii::$app->session->getFlash("error");?> </h4>
                            <?php else:?>
                                <h4 class="text-center black bold">  <?=Yii::$app->session->getFlash("success");?> </h4>
                            <?php endif;?>
                            </div>
                            <div class="payment-methods row">
                                 <div class="col-md-12 text-center">
                                            <a class="btn btn-success"  href="<?=Url::toRoute(["/course/learn","slug"=>$course->slug])?>"> Start Learning</a>
                                 </div>
                            </div>
                         </div>


                        </div>
                    </div>
                </div>

    <!-- END / COURSE TOP -->