frontend/controllers/GroupController.php
<?php

namespace frontend\controllers;

use Yii;
use frontend\models\TcCourseGroup;
use frontend\models\TcGroupSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\helpers\Url;

/**
 * GroupController implements the CRUD actions for TcCourseGroup model.
 */
class GroupController extends Controller
{
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['post'],
                ],
            ],
        ];
    }

    /**
     * Lists all TcCourseGroup models.
     * @return mixed
     */
    public function actionIndex()
    {
        // $searchModel = new TcGroupSearch();
        // $dataProvider = $searchModel->search(Yii::$app->request->queryParams);
        //
        // return $this->render('index', [
        //     'searchModel' => $searchModel,
        //     'dataProvider' => $dataProvider,
        // ]);
    }

    public function actionAddUser(){

      $g_user = new \frontend\models\TcGroupUser;
      $params= Yii::$app->request->post();
      $user = \frontend\models\User::find()->where(["email"=>$params['useremail']])->one();

      $g= \frontend\models\TcCourseGroup::find()->where(['id'=>$params['group']])->one();
      if($user==null){
          Yii::$app->session->setFlash("error","The email address you entered does not exist.");
          return $this->redirect(Url::previous());
      }
      else if($g == null){
        Yii::$app->session->setFlash("error","The group you selected does not exist.");
        return $this->redirect(Url::previous());
      }
      else if(\frontend\models\TcGroupUser::find()->where(["userid"=>$user->id,"groupid"=>$g->id])->exists()){
        Yii::$app->session->setFlash("error",$user->email.' is already added to this group "'.$g->name.'"');
        return $this->redirect(Url::previous());
      }
      $g_user->groupid=$params["group"];
      $g_user->userid= $user->id;
      $g_user->save();
      Yii::$app->session->setFlash("success",$params['useremail']." was successfully added to ".$g->name);
      return $this->redirect(Url::previous());

    }

    /**
     * Displays a single TcCourseGroup model.
     * @param integer $id
     * @return mixed
     */
    public function actionView($id)
    {
        if(Yii::$app->request->get('delete')){
            $guser= Yii::$app->request->get("guser");
            $del=\frontend\models\TcGroupUser::find()->where(["id"=>$guser])->one();
            $del->delete();
        }
      $query = \frontend\models\TcGroupUser::find()->where(["groupid"=>$id]);
      $dataProvider = new \yii\data\ActiveDataProvider([
          'query' => $query,
          // 'pagination' => [
          //     'pageSize' => 2,
          // ],
      ]);
        return $this->renderAjax('_user', [
            'model' => $this->findModel($id),
            'dataProvider'=>$dataProvider
        ]);
    }

    /**
     * Creates a new TcCourseGroup model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new TcCourseGroup();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
          Yii::$app->session->setFlash("success","Your last operation was successful.");
            return $this->redirect(Url::previous());
        } else {
          Yii::$app->session->setFlash("error","Your last operation was unsuccessful.");
          return $this->redirect(Url::previous());
            // return $this->render('create', [
            //     'model' => $model,
            // ]);
        }
    }

    /**
     * Updates an existing TcCourseGroup model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     */
    public function actionUpdate()
    {

      if (Yii::$app->request->post('hasEditable')) {
        $model = $this->findModel(Yii::$app->request->post('editableKey'));
        $post = [];
        $posted = current($_POST['TcCourseGroup']);
        $post['TcCourseGroup'] = $posted;
        \Yii::$app->response->format = \yii\web\Response::FORMAT_JSON;
        if ($model->load($post) && $model->save()) {
            return ['output'=>$model->name, 'message'=>''];
        } else {
            return ['output'=>'', 'message'=>''];
        }
      }

    }

    /**
     * Deletes an existing TcCourseGroup model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        Yii::$app->session->setFlash("success","Your last operation was successful.");
          return $this->redirect(Url::previous());
    }

    /**
     * Finds the TcCourseGroup model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return TcCourseGroup the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = TcCourseGroup::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }
}

frontend/views/group/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model frontend\models\TcCourseGroup */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="tc-course-group-form">

    <?php $form = ActiveForm::begin(); ?>

    <?= $form->field($model, 'name')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'createdate')->textInput() ?>

    <?= $form->field($model, 'createdby')->textInput() ?>

    <div class="form-group">
        <?= Html::submitButton($model->isNewRecord ? 'Create' : 'Update', ['class' => $model->isNewRecord ? 'btn btn-success' : 'btn btn-primary']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

frontend/views/group/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model frontend\models\TcGroupSearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="tc-course-group-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
    ]); ?>

    <?= $form->field($model, 'id') ?>

    <?= $form->field($model, 'name') ?>

    <?= $form->field($model, 'createdate') ?>

    <?= $form->field($model, 'createdby') ?>

    <div class="form-group">
        <?= Html::submitButton('Search', ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton('Reset', ['class' => 'btn btn-default']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

frontend/views/group/_user.php
<?php
  use frontend\models\User;
  use yii\widgets\ListView;
  use yii\widgets\Pjax;
  use yii\helpers\Url;


 ?>



 <div class="modal-content">
 <div class="modal-header">
     <button type="button" class="close" data-dismiss="modal" ><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
     <h4 class="modal-title" id="myModalLabel">Group Users<span id="group-name"></span></h4>
 </div>
     <div class="modal-body" >
         <div class="row">

             <div class="col-md-12">
               <?php Pjax::begin(["id"=>"pjax_tutors",'enablePushState' => false]); ?>
                 <?=
                     ListView::widget([
                     'dataProvider' => $dataProvider,
                     'itemOptions'=>[
                       "tag"=>"li",
                       'class'=>"_items"
                     ],
                     'options' => [
                         'tag' => 'div',
                         'class' => 'view-user-ul',
                         'id' => '',
                             ],
                     'itemView'=>function ($model) {
                        $name =User::getName($model->userid);
                        $url = Url::toRoute(["/group/view","id"=>$model->groupid,"guser"=>$model->id,"delete"=>"yes"]);
                        return $name["firstname"]." ".$name["lastname"]."<a style='float:right' data-guserid='".$model->id."' href='".$url."'><span class='fa fa-trash'></span></a>";
                     },
                         'layout' => "{summary}{items}\n {pager}",
                     ]);


                   ?>
                 <?php Pjax::end(); ?>

             </div>

         </div>

        <div class="modal-footer">
          Remove a user from this group by clicking the red trash button next to the user name
         </div>
     </div>
   </div>

frontend/views/group/create.php
<?php

use yii\helpers\Html;


/* @var $this yii\web\View */
/* @var $model frontend\models\TcCourseGroup */

$this->title = 'Create Tc Course Group';
$this->params['breadcrumbs'][] = ['label' => 'Tc Course Groups', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="tc-course-group-create">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

frontend/views/group/index.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;

/* @var $this yii\web\View */
/* @var $searchModel frontend\models\TcGroupSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Tc Course Groups';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="tc-course-group-index">

    <h1><?= Html::encode($this->title) ?></h1>
    <?php // echo $this->render('_search', ['model' => $searchModel]); ?>

    <p>
        <?= Html::a('Create Tc Course Group', ['create'], ['class' => 'btn btn-success']) ?>
    </p>

    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'filterModel' => $searchModel,
        'columns' => [
            ['class' => 'yii\grid\SerialColumn'],


            'name',
            'no of users'
            'created date',
            'createdby',

            ['class' => 'yii\grid\ActionColumn'],
        ],
    ]); ?>

</div>

frontend/views/group/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model frontend\models\TcCourseGroup */

$this->title = 'Update Tc Course Group: ' . ' ' . $model->name;
$this->params['breadcrumbs'][] = ['label' => 'Tc Course Groups', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->name, 'url' => ['view', 'id' => $model->id]];
$this->params['breadcrumbs'][] = 'Update';
?>
<div class="tc-course-group-update">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

frontend/views/group/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model frontend\models\TcCourseGroup */

$this->title = $model->name;
$this->params['breadcrumbs'][] = ['label' => 'Tc Course Groups', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="tc-course-group-view">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a('Update', ['update', 'id' => $model->id], ['class' => 'btn btn-primary']) ?>
        <?= Html::a('Delete', ['delete', 'id' => $model->id], [
            'class' => 'btn btn-danger',
            'data' => [
                'confirm' => 'Are you sure you want to delete this item?',
                'method' => 'post',
            ],
        ]) ?>
    </p>

    <?= DetailView::widget([
        'model' => $model,
        'attributes' => [
            'id',
            'name',
            'createdate',
            'createdby',
        ],
    ]) ?>

</div>