backend/models/Courses.php
<?php

namespace backend\models;

use Yii;

class Courses extends \frontend\models\Course
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'courses';
    }

    
}

frontend/models/CourseViews.php
<?php

namespace frontend\models;

use Yii;

/**
 * This is the model class for table "course_views".
 *
 * @property string $id
 * @property string $courseid
 * @property string $cookie
 * @property string $date
 */
class CourseViews extends \yii\db\ActiveRecord
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'course_views';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['courseid', 'cookie'], 'required'],
            [['courseid'], 'integer'],
            [['date'], 'safe'],
            [['cookie'], 'string', 'max' => 1000]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'courseid' => 'Courseid',
            'cookie' => 'Cookie',
            'date' => 'Date',
        ];
    }
}

frontend/controllers/CourseController.php
<?php

namespace frontend\controllers;

use Yii;
use yii\web\Response;
use frontend\models\Course;
use frontend\models\CourseInstructors;
use frontend\models\CourseParts;
use frontend\models\CourseLessons;
use frontend\models\LessonContent;
use yii\data\ActiveDataProvider;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\filters\AccessControl;
use yii\helpers\Url;
use yii\web\UploadedFile;
use frontend\models\User;
use frontend\models\Quiz;
use frontend\models\Question;
use frontend\models\Answers;
use frontend\models\CourseCoupons;
use frontend\models\CourseSettings;
use frontend\models\CourseCategory;
use frontend\models\Utility;
use frontend\models\CourseOutlineOrder;
use Foolz\SphinxQL\SphinxQL;
use Foolz\SphinxQL\Connection;
use yii\data\Pagination;
use frontend\models\CoursesIndex;
use yii\base\ErrorException;
use frontend\models\TcLessonContent;
use frontend\models\TcUploadedContent;

/**
 * CourseController implements the CRUD actions for Course model.
 */

class CourseController extends Controller
{
    public $defaultAction ="checkowner";

    public function behaviors()
    {

        return [
             'access' => [
                'class' => AccessControl::className(),

                'rules' => [
                   [
                        'actions' => ['index','apply-coupon','checkowner','details','coursecategory','search','login','autosuggestjson','language'],
                        'allow' => true,
                        'roles' => ['?'],
                    ],
                    [
                        'actions' => ['content-from-library','quiz-result','questions-display','question-modal','apply-coupon','under-the-hood','privacy','price-and-coupons','description','savegoals','getgoals','saveaudience','getaudience','saverequirements','getrequirements','target-and-requirements','addlogotovideo','language','outlinejson','login','search','autosuggestjson','lessoncomplete','finish-quiz','saveanswers','getsavedanswers','createcourse','basicinfo','savename','savereview','flagabuse','index','subscribe','learn','getsubcategory','coursecategory','coursebanner','details','promovideo','deletebanner','contents','preview','studentreport','publish','unpublish','submitforreview','settings','saveparttitle','editpart','deletepart','newunit','editunit','deleteunit','uploadnewunitvideo','uploadnewunitpresentation','downloadables','getcontents','externallinks','textcontent','deleteunitcontent','newquiz','deletequiz','editquiz','newquestion','deletequestion','updatequestion','getquestion','deletecoupon','delete','savediscussion','getdiscussions','savereply','getlastreply','saveannouncement','classroom','studentpreview','learning','saveusernote','sectionorder','sectionitemsorder','classroomnavigation','quizintro','quizquestion','savetimer'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['post'],
                ],
            ],
        ];
    }


    /**
     * Lists all Course models.
     * @return mixed
     */
     function checkOwner($loginuserid,$ownerid){
        if($loginuserid != $ownerid){
            return $this->redirect(Url::toRoute("/tutors/dashboard"));
        }

    }
    public function actionLogin(){
      return $this->redirect(Url::toRoute("/site/login"));
    }
    public function actionCreatecourse(){

        $course= new Course(['scenario' => 'isguest']);
        if($course->load(Yii::$app->request->post())){

            $transaction = $course->getDb()->beginTransaction();
            $course->owner = Yii::$app->user->id;
            $course->skill_level=1;

            if($course->save()){
                $instructors=  new CourseInstructors();
                $instructors->course_id=$course->getPrimaryKey();
                $instructors->user_id=Yii::$app->user->id;
                print_r($instructors);
                if($instructors->save())
                    {
                        $transaction->commit();
                        return $this->redirect(Url::toRoute(["basicinfo",'slug'=>$course->slug]));
                    }
            }

            print_r($course->getErrors());
        }



    }
    public function actionDetails($slug){
        Url::remember();
        $processed_amount=0;
        $coupon="";
        if(!Course::find()->where(["slug"=>$slug])->exists()){
          return $this->redirect("/site");
        }
        $course=Course::find()->where(["slug"=>$slug])->one();

        $processed_amount =Course::getPrice($course->course_id);//
        $login =  new \frontend\models\LoginForm();
        $couponForm="<form  method='get' id='coupon-form'><input type='hidden' name='". Yii::$app->request->csrfParam."' value='".Yii::$app->request->csrfToken."' /><input type='text' name='coupon_code' placeholder='Enter coupon' class='form-control'/><button id='apply-coupon' type='submit' class='btn btn-success'>Apply</button></form>";
        Yii::$app->user->returnUrl=Url::current();
        //redirect user to learn page if already enrolled.
         if(!Yii::$app->user->isGuest && \frontend\models\Enrollment::find()->where(['courseid'=>$course->course_id,"userid"=>Yii::$app->user->id])->exists()){
           return $this->redirect(Url::toRoute(["learn","slug"=>$course->slug]));
         }
         //apply coupon code
         if(Yii::$app->request->get("coupon_code")){
           $code = Yii::$app->request->get("coupon_code");
           $courseid =$course->course_id;// Yii::$app->request->get("courseid");

           if(CourseCoupons::find()->where(["courseid"=>$courseid,"coupon_code"=>$code])->exists()){
             $coupon=CourseCoupons::find()->where(["courseid"=>$courseid,"coupon_code"=>$code])->one();
             if(strtotime("today") >=strtotime($coupon->expirey_date)){
                     Yii::$app->session->setFlash("error","The applied coupon has expired.");
                     //return $this->redirect(Url::previous());
               }
            else{
              $processed_amount =Course::getPrice($course->course_id,$coupon->discount);//
              $coupon=$code;
            }
           }
           else{
             Yii::$app->session->setFlash("error",'Sorry this coupon does not exist');
            // return $this->redirect(Url::previous());
           }
         }
        // if(Course::getPrice($course->course_id)=="Free"){
        //     $buttontext="Start Learning Now";
        //     $button= '<a href="'.Url::toRoute(["/course/subscribe","slug"=>$course->slug]).'" class="mc-btn btn-style-1">'.$buttontext.'</a>';
        //
        // }
        // else{
        //     $buttontext = "Take This Courses";
        //     $button= '<a href="'.Url::toRoute(["/payment/checkout","id"=>$course->course_id]).'" class="mc-btn btn-style-1">'.$buttontext.'</a>';
        //
        // }
        /*if(!Yii::$app->request->cookies->has("tsuser")){
            Yii::$app->response->cookies->add(new \yii\web\Cookie(['name'=>"tsuser",'value'=>Yii::$app->security->generateRandomString(),'expire'=>3600 * 1000 * 24 * 365]));
        }*/
        //if it is not an instructor viewing his own course--preview
        if(Yii::$app->request->get("role")!=2 && Course::isViewed($course->course_id,Yii::$app->request->cookies->getValue("tsuser"))){
             $view = new \frontend\models\CourseViews;
                $view->courseid= $course->course_id;
                $cookie=Yii::$app->request->cookies;
                $view->cookie=$cookie->getValue("tsuser");

                $view->save();
        }

        return $this->render("coursedetails",array('coupon'=>$coupon,'processed_amount'=>$processed_amount,'couponForm'=>$couponForm,"course"=>$course,'login'=>$login,"role"=>1));


    }
    public function actionApplyCoupon(){
      $code = Yii::$app->request->post("coupon_code");
      $courseid = Yii::$app->request->post("courseid");

      if(CourseCoupons::find()->where(["courseid"=>$courseid,"coupon_code"=>$code])->exists()){
        $coupon=CourseCoupons::find()->where(["courseid"=>$courseid,"coupon_code"=>$code])->one();
        if(strtotime("today") >=strtotime($coupon->expirey_date)){
                Yii::$app->session->setFlash("error","The applied coupon has expired.");
                return $this->redirect(Url::previous());
          }
      }
      else{
        Yii::$app->session->setFlash("error",'Sorry this coupon does not exist');
        return $this->redirect(Url::previous());
      }
    }
    public function actionStudentpreview($slug){
        $role=0;
        $coupon="";
        $course=Course::find()->where(["slug"=>$slug])->one();
        $couponForm="<form  method='get' id='coupon-form'><input type='hidden' name='". Yii::$app->request->csrfParam."' value='".Yii::$app->request->csrfToken."' /><input type='text' name='coupon_code' placeholder='Enter coupon' class='form-control'/><button id='apply-coupon' type='submit' class='btn btn-success'>Apply</button></form>";
        $processed_amount =Course::getPrice($course->course_id);//
        $login =  new \frontend\models\LoginForm();
        Yii::$app->user->returnUrl=Url::current();
        if(Course::getPrice($course->course_id)=="Free"){
            $buttontext="Start Learning Now";
            if($role==2)// check if an instructor is previewing his course.
              $button= '<button class="mc-btn btn-style-1">'.$buttontext.'</button>';
            else{
                  $button ='<a href="'.Url::toRoute(["/course/subscribe","slug"=>$course->slug]).'" class="mc-btn btn-style-1">'.$buttontext.'</a>';
                }
        }
        else{
            $buttontext = "Take This Courses";
          //  $button= '<button class="mc-btn btn-style-1">'.$buttontext.'</button>';

frontend/views/course/_question.php
<?php
    use frontend\models\User;
    use yii\helpers\Url;
    use yii\web\View;
    use yii\widgets\ActiveForm;

    $this->registerJs('var userid='.json_encode(Yii::$app->user->id),View::POS_HEAD);
    //$this->registerJs('var courseid='.json_encode($course->course_id),View::POS_HEAD);
    $this->registerJs('var baseUrl='.json_encode(Url::base()),View::POS_HEAD);
    $this->registerJs('var quizid='.json_encode($quiz->q_id),View::POS_HEAD);
    $this->registerJs('var timer_counter2='.json_encode($timelimit),View::POS_HEAD);
      // 
      // $this->registerJs('var timer_counter1='.json_encode(date("Y/m/d H:i:s", time())),View::POS_HEAD);
    $this->registerJs('var timer_counter='.json_encode($timelimit),View::POS_HEAD);

?>
<link rel="stylesheet" type="text/css" href="<?=Url::base()?>/css/jquery.countdown.css">
<script type="text/x-handlebars-template" id="questions-template">

                            <h4 class="title">Question {{counter}} - {{title}}</h4>
                            <p>{{description}}</p>
                            <div class="answer">
                                <!-- <h4 class="title">Answer</h4> -->
                                <form method="get" id="ans-form" onsubmit="return false" action="saveanswers">
                                <ul class="answer-list">

                                  {{#each answers}}
                                    <li>
                                        {{#if ../multiple }}
                                        <input type="checkbox" name="checkbox[]" value="{{id}}" id="checkbox-{{id}}">
                                        <label for="checkbox-{{id}}">
                                            <i class="icon icon_check fa fa-check"></i>
                                            {{answer}}
                                        </label>
                                        {{else}}

                                          <input type="radio" name="radio-ans" value="{{id}}" id="radio-{{id}}">
                                          <label for="radio-{{id}}">
                                              <i class="icon icon_radio"></i>
                                              {{answer}}
                                          </label>
                                        {{/if}}
                                    </li>
                                {{/each}}

                                </ul>
                              </form>
                            </div>
                            <a  id="previous" class="btn btn-default pointer" data-questiontype="{{type}}" data-questionid="{{questionid}}" data-counter="{{counter}}" data-quizid="<?=$quiz->q_id?>">Previous Question</a>
                            {{#if last}}
                              <a id="finish" class="btn btn-default pointer" data-questiontype="{{type}}" data-questionid="{{questionid}}" data-counter="{{counter}}" data-quizid="<?=$quiz->q_id?>">Finish</a>
                            {{else}}
                                <a  id="next" class="btn btn-default pointer"  data-questiontype="{{type}}"  data-questionid="{{questionid}}" data-counter="{{counter}}" data-quizid="<?=$quiz->q_id?>">Next question</a>
                            {{/if}}

                            <?php  if($quiz->islimitedbytime!="No"):?>
                              <!-- <div style="padding: 15px;font-size: 20px;" class="text-right"><span>Remaining Time &nbsp;&nbsp;<i class="fa icon fa-clock-o"></i>&nbsp;&nbsp;</span><span id="clock"></span></div> -->
                            <?php endif;?>


</script>
<script type="text/x-handlebars-template" id="result-template">
     <h4 class="sm">You got {{correct}}/{{total}} Questions right</h4>
                            <table class="table-question">
                                <tbody>
                                  {{#each answers}}
                                    <tr>
                                        <td><i class="icon {{class}}"></i></td>
                                        <td class="td-quest">

                                            {{counter}}. {{question}}

                                        </td>
                                    </tr>
                                    {{/each}}
                                </tbody>
                            </table>
</script>
<section id="quizz-intro-section" class=" learn-section" style="min-height: 947px;">
        <div class="container">
            <div class="title-ct">
                <h3 class="title"><strong>Quizz <?=$quiz->counter?>: </strong><?=$quiz->q_name?> </h3>
                <!--<div class="tt-right">
                    <a href="#" class="skip"><i class="icon md-arrow-right"></i>Skip quizz</a>
                </div>-->
            </div>

            <div class="question-content-wrap">
              <?php  if($quiz->islimitedbytime!="No"):?>
                <div style="padding: 15px;font-size: 20px; padding-bottom:0" class="text-right"><span>Remaining Time &nbsp;&nbsp;<i class="fa icon fa-clock-o"></i>&nbsp;&nbsp;</span><span id="clock"></span></div>
              <?php endif;?>
                <div class="question-content">
                  <div class="text-center">  <i class="fa fa-circle-o-notch fa-spin fa-2x"></i></div>
                </div>
                <?php  //if($quiz->islimitedbytime!="No"):?>
                  <!-- <div style="padding: 15px;font-size: 20px;" class="text-right"><span>Remaining Time &nbsp;&nbsp;<i class="fa icon fa-clock-o"></i>&nbsp;&nbsp;</span><span id="clock"></span></div> -->
                <?php //endif;?>
            </div>
</section>

<?php $this->registerJsFile( Url::base().'/js/library/handlebars.js',['depends' => [\yii\web\JqueryAsset::className()]]); ?>
<?php //$this->registerJsFile( Url::base().'/js/library/jquery.countdown.min.js',['depends' => [\yii\web\JqueryAsset::className()]]); ?>
<?php $this->registerJsFile( Url::base().'/js/jquery.plugin.min.js',['depends' => [\yii\web\JqueryAsset::className()]]); ?>
<?php $this->registerJsFile( Url::base().'/js/jquery.countdown.min.js',['depends' => [\yii\web\JqueryAsset::className()]]); ?>
<?php $this->registerJsFile( Url::base().'/js/quiz.js',['depends' => [\yii\web\JqueryAsset::className()]]); ?>

frontend/views/course/_search_list_item.php
<?php
    use frontend\models\Course;
?>


                            <!-- ITEM -->

                            <?php $coursead=Course::getCourseAd($model->course_id);?>
                                <div class="coursebox">
                                    <?=Course::createGuestOtherCourseAd($coursead,"mc-item-2")?>
                                </div>



                            <!-- END / ITEM -->

frontend/views/course/basic-info.php
<?php
  use yii\bootstrap\ActiveForm;
  use yii\helpers\Url;
  use frontend\models\CourseCategory;
  use frontend\models\SkillLevel;
  use yii\helpers\ArrayHelper;
  use yii\web\View;
  use frontend\models\IsoLanguages;
  use yii\bootstrap\Button;
 ?>



<div class="main-content-title row  text-center"><h3 class="title">Basic Information</h3></div>
    <div class="main-content-body row text-center">

        <?php $form = ActiveForm::begin(['layout' => 'horizontal','fieldConfig' => [
        'template' => "{label}\n{beginWrapper}\n{input}\n{hint}\n{error}\n{endWrapper}",
        'horizontalCssClasses' => [
            'label' => 'col-sm-4 col-xs-12',
            'error' => '',
            'hint' => '',
        ],
    ],])?>
            <div class="col-md-12">
                <?=$form->field($course,"course_title")->textInput();?>
            </div>

            <div class="col-md-12">
                 <?= $form->field($course,'course_category')->dropDownList(CourseCategory::getCategory(),['class'=>'select form-control','id'=>'category_select','prompt'=>'Select category','style'=>""]) ?>
            </div>
            <div class="col-md-12">
                 <?= $form->field($course,'course_subcategory')->dropDownList(\yii\helpers\ArrayHelper::map(CourseCategory::getSubCat($course->course_category),"id","subcategory"),['class'=>'select form-control','id'=>'subcategory','prompt'=>'','style'=>""]) ?>
            </div>
            <div class="col-md-12">
              <?= $form->field($course,'skill_level')->dropDownList(ArrayHelper::map(SkillLevel::find()->all(),'id','skill_level'),['class'=>'select form-control','prompt'=>'Select skill level','style'=>""])?>
            </div>
            <div class="col-md-12">
                  <?= $form->field($course,'language')->dropDownList(IsoLanguages::getISOLanguage(),['prompt'=>'Select language'])?>
            </div>
            <div class="col-md-12">
                <?=Button::widget(["label"=>"Save","options"=>['class'=>"btn btn-success","type"=>"submit"]])?>
            </div>

        <?php ActiveForm::end()?>

    </div>

<?php
$url=Url::base();
$script=<<<EOD
$('#category_select').change(function(){
    $("#subcategory").html("");
  $.get("$url/course/getsubcategory",{"category":$(this).val()},function(data){
      data = $.parseJSON(data)

      $.each(data,function(key, value)
        {
           $("#subcategory").append('<option value=' + value.id + '>' + value.subcategory+ '</option>');
        });

  })
})
EOD;
   $this->registerJs($script);
 ?>

frontend/views/course/dashboard.php
<?php
use yii\helpers\Url;
use yii\helpers\Html;
use yii\widgets\ActiveForm;
use frontend\models\Course;
use frontend\models\User;
use frontend\models\CourseCategory;
use yii\bootstrap\Modal;
use marqu3s\summernote\Summernote;
use yii\widgets\ListView;
use yii\widgets\Pjax;
use scotthuangzl\googlechart\GoogleChart;
use yii\bootstrap\BootstrapPluginAsset;
?>
<style>
  .btn-default{
        height: 34px;
  }
  .modal-dialog {
    width: 400px;
}
</style>

   <!-- END / CONTENT BAR -->
<!-- COURSE CONCERN -->
    <section  class="tutor_content_bg">
        <div class="container">
            <?php if(Yii::$app->session->hasFlash("error")):?>
             <div class="alert alert-danger"><?=Yii::$app->session->getFlash('error')?></div>
            <?php elseif(Yii::$app->session->hasFlash("success")):?>
                <div class="alert alert-success"><?=Yii::$app->session->getFlash('success')?></div>
            <?php endif?>
            <!-- <div class="price-course">
                <i class="icon md-database"></i>
                <h3>Available Balance </h3>
                <span>$0.0</span>
                <div class="create-coures">
                    <a href="#addsection" class="mc-btn btn-style-1 popup-with-zoom-anim">Create new course</a>
                    <a href="#" class="mc-btn btn-style-5">Request Payment</a>
                </div>

            </div> -->

            <div class="row" id="dashboard_sec">
              <div class="col-md-6" id="earnings">
                <div class="col-md-12" id="monthly-earning-chart">
                  <?=
                   GoogleChart::widget(array('visualization' => 'LineChart',
                   'data' => array(
                       array('Month', 'Gross',"Net"),
                       array('Work', 11,3),
                       array('Eat', 2,4),
                       array('Commute', 2,6),
                       array('Watch TV', 2,1),
                       array('Sleep', 7,4)
                   ),

                   'options' => array("height"=>"400",
                   'title' => 'Earning for this month',
                   "legend"=>[ "position"=> "top" ],
                   'chatArea'=>["left"=>"5em","top"=>"20px","width:100%","height"=>"400"],
                   'colors'=>["#ef4132","#4caf50"]
                  )));
                  ?>
                </div>
                <div class="row col-md-12">
                    <div id="gross" class="col-sm-6  col-xs-6  col-md-6 gross-net">
                        <strong><span>Gross Revenue</span></strong>
                        <h1>$500</h1>
                    </div>
                  <div id="net" class="col-sm-6  col-xs-6 col-md-6 gross-net">
                        <span>Net Revenue</span>
                        <h1>$400</h1>
                    </div>
                </div>
                <div class="col-md-12" id="transactions">
                      <table class="table table-stripe">
                          <thead>
                            <tr><th>Transaction ID</th><th>Date</th><th>Amount</th></tr>
                          </thead>
                          <tbody>
                              <tr><td>#12345</td><td>12 Jan 2015</td><td>$20</td></tr>
                              <tr><td>#12345</td><td>12 Jan 2015</td><td>$20</td></tr>
                              <tr><td>#12345</td><td>12 Jan 2015</td><td>$20</td></tr>
                              <tr><td>#12345</td><td>12 Jan 2015</td><td>$20</td></tr>
                              <tr><td>#12345</td><td>12 Jan 2015</td><td>$20</td></tr>
                              <tr><td>#12345</td><td>12 Jan 2015</td><td>$20</td></tr>
                          </tbody>
                      </table>
                </div>

              </div>
                  <div class="col-md-6">
                    <div class="create-coures text-right">
                        <a href="#createCourseModal" data-target="#createCourseModal" data-toggle="modal"  class="custom-btn grey-btn ">
                          <span></span>
                          Create a course</a>
                        <!-- <a href="#" class="mc-btn btn-style-5">Request Payment</a> -->
                    </div>

                    <div id="tut-list-wrapper">

                      <div id="search_filter" class="col-md-12">
                          <div class="col-md-6 text-left search-div" >
                            <?php ActiveForm::begin(["method"=>"get",'options' => ['data-pjax' => true ]])?>
                              <div class="input-group add-on">
                                    <input id="searchfield" class="form-control" type="text" name="q" placeholder="Search for your course"/>
                                    <div class="input-group-btn">
                                      <button class="btn btn-default" type="submit"><i class="fa fa-search"></i></button>
                                    </div>
                                  </div>
                                <!-- <input id="searchfield" class="form-control" type="text" name="searchfilter" placeholder="Search for your course"/> -->
                            <?php ActiveForm::end();?>
                          </div>
                          <div class="col-md-6 text-right sorter-div">

                            <?php $form=ActiveForm::begin(["id"=>"sorter-form","method"=>"get",'options' => ['data-pjax' => true ]])?>
                                <select  id="sorter" name="sorter" class="form-control">
                                    <option value="newest">Sort By Newest</option>
                                    <option value="oldest">Oldest</option>
                                    <option value="title-asc">Title Ascending</option>
                                    <option value="title-desc">Title Descending</option>
                                    <option value="1">Published</option>
                                    <option value="4">Pending Publish</option>
                                    <option value="3">Pending Review</option>
                                    <option value="2">Draft</option>
                                </select>
                            <?php ActiveForm::end()?>
                          </div>
                        </div>
                        <?php Pjax::begin(["id"=>"pjax_tutors"]); ?>
                          <?=
                              ListView::widget([
                              'dataProvider' => $dataProvider,
                              'options' => [
                                  'tag' => 'div',
                                  'class' => '',
                                  'id' => 'tutor-course-list-wrapper',
                                      ],
                              'itemView'=>"_tutors_courses",
                                  'layout' => "{items}\n <div class='clear'></div>{pager}{summary}<div class='clear'></div>",
                              ]);


                            ?>
                          <?php Pjax::end(); ?>
                    </div>

                </div>
              </div>
    </section>
    <!-- END / COURSE CONCERN -->


<!-- SECTIONS -->
<div class="modal fade" id="createCourseModal" tabindex="-1" role="dialog" aria-labelledby="createCourseModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
        <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" ><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
            <h4 class="modal-title" id="myModalLabel">Create a Course</h4>
        </div>
        <div class="modal-body" >
                <div class="row">

                        <div class="row col-md-12 row">
                            <!-- start ActiveForm -->
                              <?php $form= ActiveForm::begin(['action'=>Url::base().'/course/createcourse','options'=>['method'=>"post"]])?>
                            <div class="col-md-12">
                              <?=$form->field($newcourse,'course_title')->textInput(['maxlength'=>70,"placeholder"=>"Course name max 70 characters"])->label(false)?>

                            </div>
                            <div class="col-md-12">
                              <div class="form-group">
                                <?=  Html::dropDownList("Course[course_category]",null,CourseCategory::getCategory(),['prompt'=>"Select course category",'class'=>"form-control"]) ?>
                              </div>
                            </div>
                            <div class="col-md-offset-3 col-md-offset-right-3 col-md-6">
                                <div class="form-group">
                                  <input type="submit" class="btn btn-success form-control" value="Create"/>
                                </div>
                            </div>
                        </div>
                       <?php ActiveForm::end(); ?>
                    </div>



           <div class="modal-footer">

            </div>
          </div>
        </div>

    </div>

</div>

<?php
$script=<<<EOD
$(window).resize(function(){
  drawChartw0();
});
EOD;

$this->registerJS($script);

 ?>